### ISSUE TITLE
都城菜式评价

### ISSUE THREAD

**Issue by ryancui92** [ryancui92/blog#2]
> 10 分为满分
> 
> 评价人包括 ryancui/austin/fatfat

# 每旬菜式
| 菜式 | 评分 | 评价 | 评价人 |
| --- | --- | --- | --- |
| 叉烧粉丝蒸水蛋饭 | 7.5 | 一大块蛋，叉烧是一粒粒的 | ryancui |
| 鲜沙姜爆鸡饭 | 9 |  | ryancui |
| 鲜沙姜爆鸡饭 | 9 |  | austin |
| 水煮牛肉饭 | 6.5 | 很辣，分量很足 | ryancui |
| 豉汁凉瓜炒牛肉饭 | 7 | | ryancui |
| 子萝爆鸡饭 | 7.5 | 姜味有点太重 | ryancui |
| 榨菜蒸皖鱼饭 | 7 | 皖鱼不好吃 | ryancui |
| 藤椒汁杏鲍菇焖鸡饭 | 8.5 | 并不是很辣，很好吃 | ryancui |
| 和味萝卜牛腩饭 | 9 | 萝卜牛腩味道很棒，就是牛腩粉那种味道 | ryancui |
| 黑椒杏鲍菇牛肉粒饭 | 9 | 牛肉粒很多，黑椒味道很棒 | ryancui |
| 橙汁焗骨饭 | 7.5 | 其实就是酸甜骨吧 | ryancui |
| 自制豆腐干爆鸡饭 | 7.5 | 鸡有点少，豆腐干很多 | ryancui |
| 韭王肉丝炒蛋饭 | 8 | 那次吃的很咸，但很喜欢 | ryancui |
| 家常面筋蒸滑鸡饭 | 7.5 | 面筋不够入味 | ryancui |
| 农家豆豉焖鸭饭 | 8 | 鸭还是很好吃的 | ryancui |
| 鲜沙姜爆鲜鱿饭 | 8 | | ryancui |
| 香菠京都骨饭 | 8 | 其实就是酸甜骨嘛 | ryancui |

# 热销菜式
| 菜式 | 评分 | 评价 | 评价人 |
| --- | --- | --- | --- |
| 番茄肉丝炒蛋饭 | 8 | | ryancui |
| 冬菇云耳蒸鸡腿肉饭 | 8.5 | | ryancui |
| 吉列猪扒番茄饭 | 5 | 猪扒完全不好吃 | ryancui |
| 香煎莲藕肉饼蛋脯饭 | 6 | 就是两块饼、一块肉饼一块蛋，蛋比肉好吃 | ryancui |
| 古法纸包鸡饭 | 8.5 | 吃的时候有点麻烦 | ryancui |
| 西芹云耳炒肉片饭 | 7.5 | | ryancui |

# 明炉烧味

| 菜式 | 评分 | 评价 | 评价人 |
| --- | --- | --- | --- |
| 盐焗手撕鸡饭 | 9 | | austin |
| 盐焗手撕鸡饭 | 9 | 芝麻不太够 | ryancui |
| 麻辣手撕鸡饭 | 7 | 好辣，不适合我 | ryancui |
| 明炉烧鸭饭 | 9 | 烧鸭还可以，但是只配青菜有点寡 | ryancui |
| 明炉烧鸭饭 | 9 | | austin |
| 客家咸鸡饭 | 8 | 味道不错，但鸡肉太硬了 | ryancui |

# 天天靓汤

| 菜式 | 评分 | 评价 | 评价人 |
| --- | --- | --- | --- |
| 福果腐竹煲猪肚汤 | 9 | 好喝 | austin |
| 猴头菇煲老鸡汤 | 9 | 好喝 | austin |
| 霸王花冬瓜煲猪踭汤 | 8.5 | 挺好喝 | austin |

**Comment by iroiyu** [comment]
藤椒汁杏鲍菇焖鸡饭 我觉得可以打9分
